<a href="https://colab.research.google.com/github/MiladQolami/Mathematical-tools-for-neuroscience/blob/main/Machine_Learning/IntroToPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

PyTorch is an open-source machine learning library for Python, primarily developed by Facebook's AI Research lab (FAIR).

Several giant tech companies like Meta and Microsoft use pytorch to bring machine learning to their products. Pytorch is #1 library for deep learning among developers.





In [17]:
import torch
import matplotlib.pyplot as plt
import numpy as np


# Introduction to Tensors

Tensors are fundemental data structrues in pytorch. We store infromation of input and output data in tensors. Tensors are similar to Numpy ndarrays but with additional features. So tensors can be considered as multidimensional matrices.

Tensors can have any number of dimensions and different lengths along each dimension. For example a scalar is a tensor of rank 0, a vector is a tensor of rank 1 and a matrix is a tensor with rank 2.





<center>
<img src = 'https://raw.githubusercontent.com/MiladQolami/Mathematical-tools-for-neuroscience/main/Machine_Learning/tensor.jpg'>
<center>

## Creating tensors

we can store different types of numerical data in tensors, like integers, floating numbers and complex numbers.

Lect's create some tensors.

In [19]:
t0 = torch.tensor(4)  # tensor with rank or dimension 0, ie a scalar
print(t0)
t0.ndim   # This is tensor with 0 dimension


tensor(4)

In [20]:
t1 = torch.tensor([1.0,2.3,3.6])  # A 1D tensor, a vecrot
print(t1)
t1.ndim

tensor([1.0000, 2.3000, 3.6000])


1

In [21]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]])   # A 2D tensor or a matrix
print(t2)
t2.ndim

tensor([[1, 2, 3],
        [4, 5, 6]])


2

### Tensor's data type

We can change tensor's data type by passing an optional argument

In [5]:
t2.dtype # t2 is tensor containg integers

torch.int64

In [22]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]],dtype =torch.float16)

In [23]:
t2.dtype

torch.float16

### Shape of a tensor

We can get number of rows and columns by `.shape` method

In [30]:
t2.shape # A 2D tensor with 2 rows and 3 columns

torch.Size([2, 3])

### Initializing a tensor

Similar to Numpy arrays we can initialize a tensors with zeros, ones, random values, ...

In [9]:
zero_tensor = torch.zeros(2,5)  # A tensor with 2 rows and 5 columns with zeros
print(zero_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [31]:
range_tensor = torch.arange(0,10,2)  # A tensor with values 0,2,4,6,8,10
print(range_tensor)

tensor([0, 2, 4, 6, 8])


Let's go to higher dimensions


In [36]:
t3 = torch.tensor([[[1,3,3],
                    [2,5,3],
                    [6,2,3]]])  # A 3D tensor or a cube, columns are in depth
print(t3)
t3.ndim


tensor([[[1, 3, 3],
         [2, 5, 3],
         [6, 2, 3]]])

In [35]:
t3.shape  # A 3D tensor with 1 row, 3 columns and 3 depth

torch.Size([1, 3, 3])

Let's create a tensor with shape (2,3,2)

In [13]:
t3_2 = torch.tensor([[[1,3],
                      [3,5],
                      [6,4]],

                     [[3,4],
                      [1,3],
                      [4,3]]])  # A 3D tensor with 2 rows, 3 columns and 2 depth
print(t3_2)

tensor([[[1, 3],
         [3, 5],
         [6, 4]],

        [[3, 4],
         [1, 3],
         [4, 3]]])


In [47]:
t3_2.shape

torch.Size([2, 3, 2])

In [55]:
# Exercise: Generate a tensor with 3 rows, 2 columns and 2 depth
my_tensor = ...
print(my_tensor)
print(my_tensor.shape)

## Reductions Operations

In [59]:
# Creating a tensor
a_tensor = torch.arange(start=0,end=20,step=2)

# Some frequently used data summary statistics
a_tensor.min(),a_tensor.max(),a_tensor.sum()

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
# What about mean?
a_tensor.mean()


In [65]:
a_tensor.dtype

torch.int64

`mean()` does not work when data type is too long or it is integer. To make it work we should change data type to a shorter data type

In [66]:
a_tensor.type(torch.float32).mean()

tensor(9.)

### Finding positional min and max

In [67]:
a_tensor.argmin()  # Returns index of minimum value
a_tensor.argmax()  # Returns index of maximum value

(tensor(0), tensor(9))

### Random tensors

Random tensors are important becuase in deep neural networks we start by setting weights to random values and then try to optimize those weieghts.

`start with random values ==> look at your data ==> update your weights ==> look at your dagta ==> updata your weights`

In [69]:
rand_tensor = torch.rand(3,4)  # A tensor with random values
print(rand_tensor)

tensor([[0.6053, 0.8160, 0.1115, 0.4562],
        [0.6763, 0.1552, 0.7528, 0.7381],
        [0.0916, 0.3507, 0.1014, 0.7336]])


tensor([[0.6053, 0.8160, 0.1115, 0.4562],
        [0.6763, 0.1552, 0.7528, 0.7381],
        [0.0916, 0.3507, 0.1014, 0.7336]])