<a href="https://colab.research.google.com/github/MiladQolami/Mathematical-tools-for-neuroscience/blob/main/Machine_Learning/IntroToPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

PyTorch is an open-source machine learning library for Python, primarily developed by Facebook's AI Research lab (FAIR).

Several gient tech companies like Meta and Microsoft use pytorch to bring machine learning to their products. Pytorch is #1 library for deep learning among developers.



In [1]:
import torch
import matplotlib.pyplot as plt


# Introduction to Tensors

Tensors are fundemental data structrues in pytorch. We store infromation of input and output data in tensors. Tensors are similar to Numpy ndarrays but with additional features. So tensors can be considered as multidimensional matrices.

Tensors can have any number of dimensions and different lengths along each dimension. For example a scalar is a tensor of rank 0, a vector is a tensor of rank 1 and a matrix is a tensor with rank 2.



<center>
<img src = 'https://raw.githubusercontent.com/MiladQolami/Mathematical-tools-for-neuroscience/main/Machine_Learning/tensor.jpg'>
<center>

## Creating tensors

we can store different types of numerical data in tensors, like integers, floating numbers and complex numbers.

Lect's create some tensors.

In [2]:
t0 = torch.tensor(4)  # tensor with rank or dimension 0, ie a scalar
print(t0)
t0.ndim   # This is tensor with 0 dimension

tensor(4)


0

In [3]:
t1 = torch.tensor([1.0,2.3,3.6])  # A 1D tensor, a vecrot
print(t1)
t1.ndim

tensor([1.0000, 2.3000, 3.6000])


1

In [4]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]])   # A 2D tensor or a matrix
print(t2)
t2.ndim

tensor([[1, 2, 3],
        [4, 5, 6]])


2

### Tensor's data type

We can change tensor's data type by passing an optional argument

In [5]:
t2.dtype # t2 is tensor containg integers

torch.int64

In [6]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]],dtype =torch.float16)

In [7]:
t2.dtype

torch.float16

### Shape of a tensor

We can get number of rows and columns by `.shape` method

In [8]:
t2.shape

torch.Size([2, 3])

### Initializing a tensor

Similar to Numpy arrays we can initialize a tensors with zeros, ones, random values, ...

In [9]:
zero_tensor = torch.zeros(2,5)  # A 2D tensor with zeros as elements and shape (2,5)
print(zero_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
range_tensor = torch.arange(0,10,2)
print(range_tensor)

tensor([0, 2, 4, 6, 8])


Let's go to higher dimensions


In [11]:
t3 = torch.tensor([[[1,3,3],      # A three dimensional tensor
                    [2,5,3],
                    [6,2,3]]])
print(t3)
t3.ndim

tensor([[[1, 3, 3],
         [2, 5, 3],
         [6, 2, 3]]])


3

In [12]:
t3.shape

torch.Size([1, 3, 3])

Let's create a tensor with shape (2,3,2)

In [13]:
t3_2 = torch.tensor([[[1,3],
                      [3,5],
                      [6,4]],

                     [[3,4],
                      [1,3],
                      [4,3]]])
print(t3_2)

tensor([[[1, 3],
         [3, 5],
         [6, 4]],

        [[3, 4],
         [1, 3],
         [4, 3]]])


In [14]:
t3_2.shape

torch.Size([2, 3, 2])

How can we justify this?

Inside the first bracket we have 2 'things' (seperated by commas) and that is the first dimension, inside the second bracket we have 3 thing and that is the second dimension and inside the third and the innermost bracket we have 2 things which is the third dimension

## Reductions Operations

In [35]:
# Creating a tensor
a_tensor = torch.arange(start=0,end=20,step=2)

# Some frequently used data summary statistics
a_tensor.min(),a_tensor.max(),a_tensor.sum()

(tensor(0), tensor(18), tensor(90))

In [36]:
# What about mean?
a_tensor.mean()

RuntimeError: ignored

In [37]:
a_tensor.dtype

torch.int64

`mean()` does not work when data type is too long or it is integer. To make it work we should change data type to a shorter data type

In [46]:
a_tensor.type(torch.float32).mean()

tensor(9.)

### Finding positional min and max

In [48]:
a_tensor.argmin(),a_tensor.argmax()

(tensor(0), tensor(9))